application:
  id: "papi-reconciliation-demo"
security:
  protocol: SASL_SSL
sasl:
  mechanism: PLAIN
  jaas:
    config: org.apache.kafka.common.security.plain.PlainLoginModule   required username='user'   password='password';
bootstrap:
  servers: "pkc-e8mp5.eu-west-1.aws.confluent.cloud:9092"
schema:
  registry:
    url: "https://any.eu-central-1.aws.confluent.cloud"
basic:
  auth:
    user:
      info: apiKey:apiSecret
    credentials:
      source: USER_INFO
dlq:
  topic: "DLQ_TOPIC"
